# Generated by Django 4.2.19 on 2025-03-07 12:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="Datetime the Endpoint was created"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datetime of the last modification of the Endpoint",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Universally Unique ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField(help_text="URL to an post-able endpoint")),
                ("label", models.SlugField(help_text="Identifier for this endpoint")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="If provided, this data will be passed in along with the payload",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "endpoints",
                    models.ManyToManyField(
                        help_text="Select endpoints for this integration",
                        to="django_resilient_webhook.endpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DispatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatched",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime the Endpoint was dispatched",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="If provided, data posted to the endpoint",
                        null=True,
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "endpoint",
                    models.ForeignKey(
                        help_text="The webhook endpoint which was dispactched",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_events",
                        to="django_resilient_webhook.endpoint",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Webhook through which the endpoint was dispactched",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_events",
                        to="django_resilient_webhook.webhook",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="django_resi_content_c436ae_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="webhook",
            unique_together={("content_type", "object_id", "version")},
        ),
    ]
