# Generated by Django 4.2.19 on 2025-03-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_resilient_webhook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchevent",
            name="payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="If provided, data posted to the endpoint",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="If provided, this data will be passed in along with the payload",
                null=True,
            ),
        ),
    ]
