# Generated by Django 4.2.19 on 2025-03-09 14:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_resilient_webhook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Universally Unique ID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
