# Generated by Django 4.2.19 on 2025-03-11 16:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_resilient_webhook", "0003_player_webhooks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Universally Unique ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="Datetime the event was created"),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="If provided, data posted to the endpoint",
                    ),
                ),
                (
                    "sender_endpoint",
                    models.JSONField(
                        default=dict,
                        help_text="The sender endpoint data which contains information about the sender Endpoint instance which posted this",
                    ),
                ),
                (
                    "sender_webhook",
                    models.JSONField(
                        default=dict,
                        help_text="The sender webhook data which contains information about the sender Webhook instance which posted this",
                    ),
                ),
                (
                    "dispatched_utc",
                    models.DateTimeField(help_text="UTC datetime the Endpoint was dispatched"),
                ),
                (
                    "headers",
                    models.JSONField(default=dict, help_text="The header data of the posted request"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discard-duplicate-task-name", "Discarded duplicate task"),
                            ("reject-out-of-order", "Rejected out of order"),
                            ("accepted", "Accepted"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
