name: ci

on:
  # Also on push so that codecov reports main branch coverage
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    strategy:
      fail-fast: true
      matrix:
        python: ["3.9"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction

      - name: Run tests
        env:
          DRW_GCP_WEBHOOK_QUEUE_PATH: projects/PROJECT/locations/LOCATION/queues/QUEUE
        run: pytest
